server:
    port: 8081
spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: 89520290819
        url: jdbc:postgresql://localhost:5432/springjdbc
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
